[package]
name = "grpc_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
tonic = "0.7.2"

[build-dependencies]
tonic-build = "0.7.2"

